name: Daily Workflow

on:
  schedule:
    - cron: '30 13 * * *'

  workflow_dispatch:
jobs:
  daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "GitHub sheduled Action executed!"